'use client'

import { useParams } from 'next/navigation'
import { useItinerary } from '../../../../hooks/useItinerary'
import { format } from 'date-fns'

export default function PrintItineraryPage() {
  const params = useParams()
  const { itinerary, loading } = useItinerary(params.id as string)

  if (loading || !itinerary) {
    return (
      <div className="p-8">
        <p>Loading itinerary...</p>
      </div>
    )
  }

  return (
    <div className="p-8 max-w-4xl mx-auto print:p-4">
      <style jsx global>{`
        @media print {
          body {
            background: white;
          }
          .no-print {
            display: none;
          }
        }
      `}</style>

      <div className="mb-8">
        <h1 className="text-4xl font-bold mb-2">{itinerary.title}</h1>
        <p className="text-lg text-gray-600 mb-4">
          {itinerary.cities.join(', ')}
        </p>
        <div className="flex gap-4 text-sm text-gray-600">
          <span>
            <strong>Start:</strong> {format(new Date(itinerary.startDate), 'MMM d, yyyy')}
          </span>
          <span>
            <strong>End:</strong> {format(new Date(itinerary.endDate), 'MMM d, yyyy')}
          </span>
          {itinerary.totalCost && (
            <span>
              <strong>Estimated Cost:</strong> ¥{itinerary.totalCost.toLocaleString()}
            </span>
          )}
        </div>
      </div>

      <div className="space-y-8">
        {itinerary.days.map((day) => {
          const date = new Date(day.date)
          return (
            <div key={day.day} className="page-break-inside-avoid">
              <div className="border-b-2 border-gray-300 pb-2 mb-4">
                <h2 className="text-2xl font-bold">Day {day.day}</h2>
                <p className="text-gray-600">
                  {format(date, 'EEEE, MMMM d, yyyy')}
                </p>
              </div>

              <div className="space-y-4">
                {day.activities.map((activity, index) => (
                  <div key={index} className="border-l-4 border-primary pl-4 pb-4">
                    <div className="flex items-start justify-between mb-2">
                      <h3 className="text-xl font-semibold">{activity.name}</h3>
                      <span className="text-sm text-gray-600">
                        {activity.startTime} - {activity.endTime}
                      </span>
                    </div>
                    <p className="text-gray-700 mb-1">
                      <strong>Location:</strong> {activity.location.name}
                    </p>
                    <p className="text-sm text-gray-600 mb-2">
                      {activity.location.address}
                    </p>
                    {activity.notes && (
                      <p className="text-gray-700 italic">{activity.notes}</p>
                    )}
                    <span className="inline-block mt-2 px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded">
                      {activity.type}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )
        })}
      </div>

      <div className="mt-8 pt-8 border-t border-gray-300 text-center text-sm text-gray-600 no-print">
        <p>Generated by Japan Itinerary System</p>
        <button
          onClick={() => window.print()}
          className="mt-4 px-6 py-2 bg-primary text-white rounded-button hover:bg-primary-dark"
        >
          Print Itinerary
        </button>
      </div>
    </div>
  )
}

